services:
  - type: web
    name: sync-beats-sockets
    runtime: node
    plan: free
    buildCommand: cd sockets && npm install
    startCommand: cd sockets && npm start
    envVars:
      - key: PORT
        value: 10000
      - key: NODE_ENV
        value: production
